// <auto-generated />
using System;
using FactoryManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FACTORY_MANAGEMENT_SYSTEM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260702114218_CreateLayoutTable")]
    partial class CreateLayoutTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FactoryManagementSystem.Entities.CC", b =>
                {
                    b.Property<int>("CCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CCId"));

                    b.Property<string>("CCNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CCId");

                    b.ToTable("CCs");
                });

            modelBuilder.Entity("FactoryManagementSystem.Entities.Layout", b =>
                {
                    b.Property<int>("LayoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LayoutId"));

                    b.Property<int>("CCId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OperationId")
                        .HasColumnType("int");

                    b.Property<int?>("OperationMasterOperationId")
                        .HasColumnType("int");

                    b.Property<int>("OperationSequence")
                        .HasColumnType("int");

                    b.HasKey("LayoutId");

                    b.HasIndex("CCId");

                    b.HasIndex("OperationMasterOperationId");

                    b.ToTable("Layouts");
                });

            modelBuilder.Entity("FactoryManagementSystem.Entities.Line", b =>
                {
                    b.Property<int>("LineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LineId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("LineId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("FactoryManagementSystem.Entities.OperationMaster", b =>
                {
                    b.Property<int>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperationId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredGrade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SMV")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OperationId");

                    b.ToTable("OperationMasters");
                });

            modelBuilder.Entity("FactoryManagementSystem.Entities.Zone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZoneId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZoneId");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("FactoryManagementSystem.Entities.Layout", b =>
                {
                    b.HasOne("FactoryManagementSystem.Entities.CC", "CC")
                        .WithMany()
                        .HasForeignKey("CCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FactoryManagementSystem.Entities.OperationMaster", "OperationMaster")
                        .WithMany()
                        .HasForeignKey("OperationMasterOperationId");

                    b.Navigation("CC");

                    b.Navigation("OperationMaster");
                });

            modelBuilder.Entity("FactoryManagementSystem.Entities.Line", b =>
                {
                    b.HasOne("FactoryManagementSystem.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });
#pragma warning restore 612, 618
        }
    }
}
